spring:
  datasource:
    url: jdbc:postgresql://34.97.55.121:5432/postgres
    username: postgres
    password: "!q2w3e4r"
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    generate-ddl: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
    show-sql: true
  #  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
  jackson.serialization.indent_output: true
  devtools:
    livereload:
      enabled: true
